giang/config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  get 'comments/edit'

  devise_for :users
  resources :statuses do
  	resources :comments
  end
  root 'statuses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

giang/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :author
      can :create, Status
      can :update, Status
      can :read, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

giang/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

giang/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :status
end

giang/app/models/status.rb
class Status < ApplicationRecord
	has_many :comments 
end

giang/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 ROLES = %i[admin author]

def roles=(roles)
  roles = [*roles].map { |r| r.to_sym }
  self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
end

def roles
  ROLES.reject do |r|
    ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
  end
end

def has_role?(role)
  roles.include?(role)
end
end

giang/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :username) }
  end
end

giang/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @status = Status.find(params[:status_id])
    @comment= @status.comments.build(comment_params)
  	@comment.save

  	redirect_to @status
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    
    redirect_to Status.find(params[:status_id])
  end

  def edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def comment_params
      params.require(:comment).permit(:status_id, :text)
    end

end

giang/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
   load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:title, :post)
    end
end

giang/app/helpers/application_helper.rb
module ApplicationHelper
end

giang/app/helpers/comments_helper.rb
module CommentsHelper
end

giang/app/helpers/statuses_helper.rb
module StatusesHelper
end

giang/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

giang/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

giang/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

giang/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

giang/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% if  user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, class: 'navbar-brand', :method => :delete %>
      <% end %>
      <% if  user_signed_in? %>
        <%= link_to 'Personal', destroy_user_session_path, class: 'navbar-brand', :method => :delete %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

giang/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

giang/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Giang" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Giang" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

giang/app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :status_title %>
  </div>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post, id: :status_post, :size => '50x10'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

giang/app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

giang/app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xin chào tới Blog Giang</h1>
    <% @statuses.each do |status| %>
        <h2><%= link_to status.title, status %></h2>
        <%= time_ago_in_words status.created_at %>
        <p>
          <%= truncate status.post %>         
        </p>
    <% end %>
<br>

<%= link_to 'New Status', new_status_path %>

giang/app/views/statuses/new.html.erb
<h1>Thông tin mới</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

giang/app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Thông tin chi tiết</h1>
<p>
  <strong>Title:</strong>
  <%= @status.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @status.post %>
</p>

<h2>Bình luận</h2>
	<% @status.comments.each do |comment| %>
        <p><%= comment.text %></p>
        <p><%= time_ago_in_words comment.created_at %> trước </p>
        <p>
          <%= link_to 'Xóa bình luận', [@status, comment], :method => :delete, :confirm => 'Chắc chắn bạn muốn xóa!'%> 
        </p>
  <% end %>
<p>

<%= form_for [@status, @status.comments.build] do |form|%>
	 <p><%= form.text_area :text, :size => '50x10' %></p>
	 <%= form.submit "Đăng bình luận"%>
<% end %>

<%= link_to 'Thay đổi', edit_status_path(@status) %> 
|
<%= link_to 'Trở về', statuses_path %>
|
<%= link_to 'Xóa', @status, :method => :delete, :confirm => "Bạn có muốn xóa không ?" %>
</p>